id = "nestjs-snippets"
name = "NestJS Snippets"
version = "0.1.0"
schema_version = 1
authors = ["Ayberk Gezer <ayberkgezer@outlook.com>"]
description = "NestJS snippets for Zed IDE. A collection of NestJS snippets to improve your development speed."
repository = "https://github.com/ayberkgezer/nestjs-snippets"
snippets = "./snippets/typescript.json"
